type Feature =
  | 'countries'
  | 'cities'
  | 'airports'
  | 'transportation'
  | 'accommodation'
  | 'districts'
  | 'attractions'
  | 'parks'
  | 'food'
  | 'drink'
  | 'restaurants'
  | 'bars'
  | 'cafes'
  | 'bakeries'
  | 'chocolatiers'
  | 'gelaterias'
  | 'markets'
  | 'supermarkets'
  | 'departmentStores'
  | 'clothingStores'
  | 'interiorDesignStores'
  | 'technologyStores'
  | 'audioStores'
  | 'kitchenStores'
  | 'stationeryStores'
  | 'bookStores'
  | 'japaneseStores'
  | 'bicycleStores'
  | 'outdoorStores'
  | 'tennisStores'
  | 'uniqueElements'
  | 'nostalgiaEffect';

export type Features = {
  [K in Feature]?: string[];
};
